[package]
authors = ["Lua Zhi Zhan <zhizhan@sign.com>"]
description = "Bindings for CosmWasm contracts to call into custom modules of Sign"
edition = "2021"
license = "Apache-2.0"
name = "s-std"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all instantiate/execute/query exports
library = []

[dependencies]
cosmwasm-std = {version = "1.0.0"}
cw-utils = "0.13.2"
cw721 = "0.13.2"
cw721-base = {version = "0.13.2", features = ["library"]}
schemars = "0.8.8"
serde = {version = "1.0.137", default-features = false, features = ["derive"]}
thiserror = {version = "1.0.31"}

[dev-dependencies]
cosmwasm-schema = "1.0.0"
