[package]
name = "s1"
version = "0.1.0"
edition = "2021"

authors = ["Lua Zhi Zhan <zhizhan@sign.net>"]
description = "Definition and types for the S1 interface"
license = "Apache-2.0"
repository = "https://github.com/sign-net/sign-contracts"
homepage = "https://sign.net"

[dependencies]
cosmwasm-std = { version = "1.0.0" }
cw-utils = "0.13.2"
serde = { version = "1.0.137", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.31" }
s-std = { path = "../s-std" }
